#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Time-Duration
Version  : 1.20
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/N/NE/NEILB/Time-Duration-1.20.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/N/NE/NEILB/Time-Duration-1.20.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libt/libtime-duration-perl/libtime-duration-perl_1.20-1.debian.tar.xz
Summary  : 'rounded or exact English expression of durations'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Time-Duration-license
Requires: perl-Time-Duration-man

%description
This archive contains the distribution Time-Duration,
version 1.20:
rounded or exact English expression of durations

%package license
Summary: license components for the perl-Time-Duration package.
Group: Default

%description license
license components for the perl-Time-Duration package.


%package man
Summary: man components for the perl-Time-Duration package.
Group: Default

%description man
man components for the perl-Time-Duration package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Time-Duration-1.20
mkdir -p %{_topdir}/BUILD/Time-Duration-1.20/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Time-Duration-1.20/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Time-Duration
cp LICENSE %{buildroot}/usr/share/doc/perl-Time-Duration/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Time/Duration.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Time-Duration/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Time::Duration.3
